FROM node:18

# Create app directory
WORKDIR /home/openbackhaul/typeApprovalRegister/

# Bundle app source
COPY . .

# Install npm packages for client & Create build for react application
RUN cd ./client && npm ci --only=production && npm run build

# Install npm packages for server
RUN cd ./server && npm ci --only=production

EXPOSE 3025

#Command to start the application
CMD ["sh", "-c", "cd ./server && node index.js"]